### ISSUE TITLE
--repo not working with github (and therefore ALL)

### ISSUE THREAD

**Issue by oliv3** [linuxmao-org/linuxmao-logiciels.py#2]
```bash
$ ./linuxmao-logiciels.py --repo ALL
adljack - v1.1.0 - https://github.com/jpcima/adljack/
Traceback (most recent call last):
  File "./linuxmao-logiciels.py", line 145, in <module>
    get_github_latest()
  File "./linuxmao-logiciels.py", line 53, in get_github_latest
    latest_release = r.json()['tag_name']
KeyError: 'tag_name'
```

**Comment by oliv3** [comment]
Same result with `./linuxmao-logiciels.py --repo github`

**Comment by erwan35** [comment]
les exceptions ne sont pas encore bien gérées :) Je suppose que tu n'as pas renseigné tes identifiants github dans le fichier linuxmao-logiciels.ini ?

**Comment by oliv3** [comment]
Bien sûr que si ! C'est même la première chose que j'ai faite.

**Comment by erwan35** [comment]
bizarre alors :) Il faut que je gère mieux le truc pour comprendre ce qu'il se passe alors :)

**Comment by erwan35** [comment]
Hello,

J'ai ajouté ce truc pour essayer de comprendre ce qu'il se passe :)

https://github.com/linuxmao-org/linuxmao-logiciels.py/commit/337bde67077a8112d08d6987a1496cb06883135f

Merci de me dire ce que cela donne.

Erwan

**Comment by oliv3** [comment]
`Exception: Problème de connexion à github. 401 <Response [401]>`

401 == http unauthorized, pourtant, j'ai bien renseigné mon login / password dans le .ini

**Comment by erwan35** [comment]
As-tu déjà eu des retours de github ou jamais (dans ce cas, le soucis est ailleurs) ?

Que donne un
`curl -u username https://api.github.com/user`

Merci

**Comment by oliv3** [comment]
```sh
$ curl -u oliv3 https://api.github.com/oliv3
Enter host password for user 'oliv3':
{
  "message": "Must specify two-factor authentication OTP code.",
  "documentation_url": "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}
```
Petit souci si le 2FA est activé

**Comment by erwan35** [comment]
Hello,

Il suffit de créer un token et de remplacer ton mot de passe dans github_pass par le token et ça fonctionne (en tout cas ici).

A+
Erwan

**Comment by erwan35** [comment]
Merci, c'est mergé.

Je clos ce truc du coup.
