### ISSUE TITLE
New version wrongly detected

### ISSUE THREAD

**Issue by oliv3** [linuxmao-org/linuxmao-logiciels.py#3]
Just added an entry for [Le Biniou](https://gitlab.com/lebiniou/lebiniou) using sqlitebrowser:

![linuxmao-lebiniou](https://user-images.githubusercontent.com/84910/54478862-3e689600-4817-11e9-9b8d-26f2a74f4fc0.png)

Please note that **without the trailing slash** in the URL it would crash like this:
```sh
$ ./linuxmao-logiciels.py --repo gitlab
geonkick - v1.1 - https://gitlab.com/quamplex/geonkick/
http://gitlab.com/api/v4/projects/quamplex%2Fgeonkick
https://gitlab.com/api/v4/projects/3020274/releases
---
lebiniou - version-3.30 - https://gitlab.com/lebiniou/lebiniou
http://gitlab.com/api/v4/projects/lebiniou%2Flebinio
Traceback (most recent call last):
  File "./linuxmao-logiciels.py", line 143, in <module>
    get_gitlab_latest()
  File "./linuxmao-logiciels.py", line 97, in get_gitlab_latest
    project_id = r.json()['id']
KeyError: 'id'
```
So, I added a "/". Latest tag in the repository is: `version-3.30`.
Here is the output:
```sh
$ ./linuxmao-logiciels.py --repo gitlab
geonkick - v1.1 - https://gitlab.com/quamplex/geonkick/
http://gitlab.com/api/v4/projects/quamplex%2Fgeonkick
https://gitlab.com/api/v4/projects/3020274/releases
---
lebiniou - version-3.30 - https://gitlab.com/lebiniou/lebiniou/
http://gitlab.com/api/v4/projects/lebiniou%2Flebiniou
https://gitlab.com/api/v4/projects/8572288/releases
 New release available : version-3.25
---
```
which is obviously wrong.

**Comment by erwan35** [comment]
Hello,

Je pense que c'est parce que tu as commencé par releaser la 3.30, puis 3.29 jusqu'à la 3.25.

Tu comptes releaser la version 3.31 quand ? Tu vas me répondre que je n'ai rien testé :)

Je veux voir si je catche le truc avec :
`latest_release = r.json()[0]['tag_name']`

Vu le peu de logiciels actuellement sur gitlab, je suis un peu fainéant et ça m'embête de devoir embarquer trop de dépendances comme https://github.com/python-gitlab/python-gitlab par exemple ou de devoir bricoler tricky un truc "juste" pour lebiniou :)

A+
Erwan

**Comment by erwan35** [comment]
En ce qui concerne le /, j'étais aussi tombé sur cette histoire. 

J'ai donc ajouté un check complémentaire pour gitlab et github : 
https://github.com/linuxmao-org/linuxmao-logiciels.py/commit/5b407422c2bb80d7ba7031c43b6bc7c100a3e807

Mercu

**Comment by oliv3** [comment]
1. La 3.31 est pas encore sortie, j'attends que tavasti finisse ses plugins. **Et** que tu la testes :)
2. J'éspère pour vous qu'il n'y aura pas **que** [Le Biniou](https://gitlab.com/lebiniou/lebiniou) sur [GitLab](https://gitlab.com/) :)
3. Les releases GitLab sont basées sur les **tags**, donc dans gitlab le premier dans la liste est le plus récent, là t'as du récupérer le dernier (enfin, le dernier tag avec des release notes, sinon tu aurais eu la 3.24). Donc il suffirait tout simplement d'inverser la liste, je pense.
